### ISSUE TITLE
How to make collaboraonline work with nextcloud

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/collabora_ynh#10]
I was able to install collaboraonline but was not able to make it work with nextcloud.
Can you please explain it how to make it work with nextcloud?

**Comment by Rafi594** [comment]
This app is notworking at this moment because I don't know how to allow nextcloud to frame collabora

Help would be welcome :)

**Comment by lapineige** [comment]
I was able to use it on my server* since that change https://github.com/YunoHost-Apps/collaboraonline_ynh/commit/a03410d5434ff95055bd52f7e499a84c8b68b450
But now I've a 502 bad gateway.
* Collabora and Nextcloud installed on the same computer

And I couldn't find a way to use it from another server.

**Comment by Rafi594** [comment]
I have updated the nginx config https://github.com/YunoHost-Apps/collaboraonline_ynh/commit/c40b83809eed87d67ff7a95774d66570b02f4be4. I will try on my server.

**Comment by Rafi594** [comment]
It still doesn't work for me. @Lapineige is the app work for you ?

I would need someone who knows the nginx configuration better than me.

**Comment by lapineige** [comment]
I'll give it a try :)

**Comment by anmol26s** [comment]
maybe your loolwsd file is too old and need update?
https://github.com/YunoHost-Apps/collaboraonline_ynh/blob/master/conf/loolwsd.xml

**Comment by anmol26s** [comment]
This nginx config works for docker: https://github.com/anmol26s/collaboradocker_ynh/blob/master/conf/nginx.conf

**Comment by cyrillehamel** [comment]
i think it doesen't work because of a missing location for the admin page in the nginx configuration , if you look at the official config file exemple (https://www.collaboraoffice.com/code/nginx-reverse-proxy/ ) ,there are 2 location missing in our nginx config file , one is for the admin page and the other one ( /hosting/capabilities ) is for using collabora in the nextcloud android client (this feature was add with the lastest release of collabora)

**Comment by Rafi594** [comment]
Fixed on https://github.com/YunoHost-Apps/collaboraonline_ynh/tree/fix-config
