### ISSUE TITLE
"Welcome to nginx on Debian!" screen

### ISSUE THREAD

**Issue by pankisiel** [YunoHost-Apps/collabora_ynh#7]
hi there,
after a sucsessfull install i am redirected to the "Welcome to nginx on Debian!" screen. Is there anything i missed. Do i neeed to install Docker?
I know the whole project is in progress.. but maybe this feedback helps.

**Comment by raphaeljolivet** [comment]
Same here.
I installed the app on "/" on a dedicated domain,  but I get only "Welcome to nginx"

**Comment by Rafi594** [comment]
Hello

You can try to access to this url https://your_domain.com/loleaflet/dist/admin/admin.html

**Comment by raphaeljolivet** [comment]
Now I get the error :
**502 Bad Gateway** 

It was reported in another issue but I cannot find it anywhere.

Anyway, I see nothing running on the backend port (9980), and I don't see any comand to start the backend or setup a service in the  `install` script, like here : 

https://github.com/CollaboraOnline/Docker-CODE/blob/master/scripts/start-libreoffice.sh

**Comment by Rafi594** [comment]
Can tou try `systemctl status loolwsd.service` and paste the result here

**Comment by raphaeljolivet** [comment]
● loolwsd.service - LibreOffice Online WebSocket Daemon
   Loaded: loaded (/lib/systemd/system/loolwsd.service; enabled)
   Active: failed (Result: start-limit) since Mon 2018-02-05 14:32:17 CET; 5h 6min ago
 Main PID: 10261 (code=exited, status=70)

Feb 05 14:32:16 ns395636.ip-176-31-120.eu loolwsd[10261]: <shutdown>-10261 13:32:16.794198 [ loolwsd ] WRN  Waking up dead poll thread [websrv_poll], started: false, finished: ...ket.hpp:512
Feb 05 14:32:16 ns395636.ip-176-31-120.eu loolwsd[10261]: <shutdown>-10261 13:32:16.794239 [ loolwsd ] WRN  Waking up dead poll thread [websrv_poll], started: false, finished: ...ket.hpp:512
Feb 05 14:32:16 ns395636.ip-176-31-120.eu systemd[1]: loolwsd.service: main process exited, code=exited, status=70/n/a
Feb 05 14:32:16 ns395636.ip-176-31-120.eu systemd[1]: Unit loolwsd.service entered failed state.
Feb 05 14:32:17 ns395636.ip-176-31-120.eu systemd[1]: loolwsd.service holdoff time over, scheduling restart.
Feb 05 14:32:17 ns395636.ip-176-31-120.eu systemd[1]: Stopping LibreOffice Online WebSocket Daemon...
Feb 05 14:32:17 ns395636.ip-176-31-120.eu systemd[1]: Starting LibreOffice Online WebSocket Daemon...
Feb 05 14:32:17 ns395636.ip-176-31-120.eu systemd[1]: loolwsd.service start request repeated too quickly, refusing to start.
Feb 05 14:32:17 ns395636.ip-176-31-120.eu systemd[1]: Failed to start LibreOffice Online WebSocket Daemon.
Feb 05 14:32:17 ns395636.ip-176-31-120.eu systemd[1]: Unit loolwsd.service entered failed state.

**Comment by raphaeljolivet** [comment]
Actually, I tried to launch it manually, and I saw that 
/etc/loolwsd/loolwsd.xml is malformed : is does not contain the starting "config" tag.

**Comment by Rafi594** [comment]
You can try to uninstall and reinstall the app I have solved the problem

**Comment by raphaeljolivet** [comment]
Hi,

I have reinstalled te app. 
The service loolwsd now runs correctly both on port 9981 and 9980, but I am still getting error 502 gateway when trying to connect from the outside world.

Do you have it working on your side with the current config ?

**Comment by Rafi594** [comment]
Yes I have tested and I have the same problem on the CI https://ci-apps-dev.yunohost.org/jenkins/job/collaboraonline_ynh%20(Rafi59)/9/console

**Comment by raphaeljolivet** [comment]
Wow,  I didn't knowYNH had a custom CI infrastructure ...
That's nice !

**Comment by raphaeljolivet** [comment]
I have looked in the System logs and I see this : 
ERR  FileServerRequestHandler::NotAuthenticated: No authentication information found| wsd/FileServer.cpp:354
